name: Deploy Personal Site

on:
  push:
    branches:
      - gatsby-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.DEPLOY_PERSONAL_SITE }}
          deploy-branch: master